### ISSUE TITLE
Visual Studio frequently is "Busy"

### ISSUE THREAD

**Issue by MatthewSteeples** [georgeduckett/TeamCoding#13]
I'm not sure how to pull up more information on this issue, but we find that when we have this extension enabled that Visual Studio spends a lot of time being "Busy" and unresponsive.

Are there any easy pieces that can be moved off the UI thread or made async?

This may be my misunderstanding something, but is there a reason that there's an OpenFilesLock in LocalIDEModel? I thought the point of the ConcurrentDictionary was that you didn't need locks to access and make changes to it

**Comment by georgeduckett** [comment]
Hi, I've been meaning to try and look into this sort of thing for a while now, however I've not as yet found an easy way to get enough details to properly troubleshoot issues.

I've looked at `OpenFilesLock` and can't see why I put that in either. I've removed it for now, and also changed somewhere I had a `Thread.Sleep` to an `await Task.Delay` which was causing a few issues.

See release [v1.0.372](https://github.com/georgeduckett/TeamCoding/releases/tag/v1.0.372). I've not published it to the marketplace as I've not done much testing yet.

When I get some more free time I'll take a closer look at opportunities to move off of the UI thread.

**Comment by MatthewSteeples** [comment]
Another optimisation (sorry it's a bit "drive-by", may get time to do some measuring and changes myself after the weekend) might be to use Reactive Extensions instead of the DelayedEvent class might be beneficial. You can make it only process one event at a time and ignore further events until the processing has finished etc. May not specifically free up the UI thread but might help reduce the amount of processing that needs to be done in general

http://rxwiki.wikidot.com/101samples#toc25

**Comment by georgeduckett** [comment]
Reactive Extensions does look interesting. If Delayed event could be constructed to use that internally (or maybe change the class, requiring larger changes) it might be worth moving to a standard library rather than my custom class. In theory the custom class should ignore incoming events while processing since the invoking thread would wait on the lock before starting the timer again: https://github.com/georgeduckett/TeamCoding/blob/487d89741b7c459385718e6c50eef125bb97dc10/TeamCoding/Events/DelayedEvent.cs#L64-L69
I'd hope Rx would be more efficient though and a lot less code.

If you did have time to do some profiling/measuring I'd be very keen to see the results and am happy to work through anything it brings up.

**Comment by MatthewSteeples** [comment]
Removing the lock on the dictionary has made a massive difference, to the extent that I just went to enable the extension to do some real-project testing and found it was already enabled!

Regarding Rx, I thought there was already something that would basically only process one response at a time and always only process the latest event (which is what I'm assuming you were after here) but I can't seem to find it. The closest I've got is Throttle (which ignores events until there's been a gap)

**Comment by georgeduckett** [comment]
Sorry for delayed response; just got back from long bank holiday weekend.

That's great news. It could be that dictionary lock, however I did also made a change relating to CodeSense (the `Thread.Sleep` => `Task.Delay` change). It could be that change that made the difference; I usually develop on VS Community which doesn't use CodeSense so that might explain why I didn't notice any issue. I did make the change on professional though, hence noticing it that time.

Throttle sounds like exactly what I'm after. Basically I want to not send an update while the user us quickly typing, only sending an update once there's a gap.
